// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `map.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include "map.h"
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/BasicStream.h>
#include <IceUtil/Iterator.h>
#include <IceUtil/PopDisableWarnings.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 306
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 2
#       error Ice patch level mismatch!
#   endif
#endif

namespace
{

const ::std::string __RobotPath__OptimalPath__calcOptimalPath_name = "calcOptimalPath";

}

namespace Ice
{
}
::IceProxy::Ice::Object* ::IceProxy::RobotPath::upCast(::IceProxy::RobotPath::OptimalPath* p) { return p; }

void
::IceProxy::RobotPath::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::RobotPath::OptimalPath>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::RobotPath::OptimalPath;
        v->__copyFrom(proxy);
    }
}

::RobotPath::edgeArray
IceProxy::RobotPath::OptimalPath::calcOptimalPath(const ::std::string& __p_start, const ::RobotPath::edgeArray& __p_edges, const ::Ice::Context* __ctx)
{
    __checkTwowayOnly(__RobotPath__OptimalPath__calcOptimalPath_name);
    ::IceInternal::Outgoing __og(this, __RobotPath__OptimalPath__calcOptimalPath_name, ::Ice::Normal, __ctx);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_start);
        __os->write(__p_edges);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    if(!__og.invoke())
    {
        try
        {
            __og.throwUserException();
        }
        catch(const ::Ice::UserException& __ex)
        {
            ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
            throw __uue;
        }
    }
    ::RobotPath::edgeArray __ret;
    ::IceInternal::BasicStream* __is = __og.startReadParams();
    __is->read(__ret);
    __og.endReadParams();
    return __ret;
}

::Ice::AsyncResultPtr
IceProxy::RobotPath::OptimalPath::begin_calcOptimalPath(const ::std::string& __p_start, const ::RobotPath::edgeArray& __p_edges, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__RobotPath__OptimalPath__calcOptimalPath_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RobotPath__OptimalPath__calcOptimalPath_name, __del, __cookie);
    try
    {
        __result->prepare(__RobotPath__OptimalPath__calcOptimalPath_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_start);
        __os->write(__p_edges);
        __result->endWriteParams();
        __result->invoke();
    }
    catch(const ::Ice::Exception& __ex)
    {
        __result->abort(__ex);
    }
    return __result;
}

#ifdef ICE_CPP11

::Ice::AsyncResultPtr
IceProxy::RobotPath::OptimalPath::__begin_calcOptimalPath(const ::std::string& __p_start, const ::RobotPath::edgeArray& __p_edges, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (const ::RobotPath::edgeArray&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
{
    class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
    {
    public:

        Cpp11CB(const ::std::function<void (const ::RobotPath::edgeArray&)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
            ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
            _response(responseFunc)
        {
            CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
        }

        virtual void completed(const ::Ice::AsyncResultPtr& __result) const
        {
            ::RobotPath::OptimalPathPrx __proxy = ::RobotPath::OptimalPathPrx::uncheckedCast(__result->getProxy());
            ::RobotPath::edgeArray __ret;
            try
            {
                __ret = __proxy->end_calcOptimalPath(__result);
            }
            catch(const ::Ice::Exception& ex)
            {
                Cpp11FnCallbackNC::exception(__result, ex);
                return;
            }
            if(_response != nullptr)
            {
                _response(__ret);
            }
        }
    
    private:
        
        ::std::function<void (const ::RobotPath::edgeArray&)> _response;
    };
    return begin_calcOptimalPath(__p_start, __p_edges, __ctx, new Cpp11CB(__response, __exception, __sent));
}
#endif

::RobotPath::edgeArray
IceProxy::RobotPath::OptimalPath::end_calcOptimalPath(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __RobotPath__OptimalPath__calcOptimalPath_name);
    ::RobotPath::edgeArray __ret;
    if(!__result->__wait())
    {
        try
        {
            __result->__throwUserException();
        }
        catch(const ::Ice::UserException& __ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
        }
    }
    ::IceInternal::BasicStream* __is = __result->__startReadParams();
    __is->read(__ret);
    __result->__endReadParams();
    return __ret;
}

const ::std::string&
IceProxy::RobotPath::OptimalPath::ice_staticId()
{
    return ::RobotPath::OptimalPath::ice_staticId();
}

::IceProxy::Ice::Object*
IceProxy::RobotPath::OptimalPath::__newInstance() const
{
    return new OptimalPath;
}

::Ice::Object* RobotPath::upCast(::RobotPath::OptimalPath* p) { return p; }

namespace
{
const ::std::string __RobotPath__OptimalPath_ids[2] =
{
    "::Ice::Object",
    "::RobotPath::OptimalPath"
};

}

bool
RobotPath::OptimalPath::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__RobotPath__OptimalPath_ids, __RobotPath__OptimalPath_ids + 2, _s);
}

::std::vector< ::std::string>
RobotPath::OptimalPath::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__RobotPath__OptimalPath_ids[0], &__RobotPath__OptimalPath_ids[2]);
}

const ::std::string&
RobotPath::OptimalPath::ice_id(const ::Ice::Current&) const
{
    return __RobotPath__OptimalPath_ids[1];
}

const ::std::string&
RobotPath::OptimalPath::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::RobotPath::OptimalPath";
    return typeId;
#else
    return __RobotPath__OptimalPath_ids[1];
#endif
}

::Ice::DispatchStatus
RobotPath::OptimalPath::___calcOptimalPath(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::std::string __p_start;
    ::RobotPath::edgeArray __p_edges;
    __is->read(__p_start);
    __is->read(__p_edges);
    __inS.endReadParams();
    ::RobotPath::edgeArray __ret = calcOptimalPath(__p_start, __p_edges, __current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(__ret);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

namespace
{
const ::std::string __RobotPath__OptimalPath_all[] =
{
    "calcOptimalPath",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};

}

::Ice::DispatchStatus
RobotPath::OptimalPath::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__RobotPath__OptimalPath_all, __RobotPath__OptimalPath_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __RobotPath__OptimalPath_all)
    {
        case 0:
        {
            return ___calcOptimalPath(in, current);
        }
        case 1:
        {
            return ___ice_id(in, current);
        }
        case 2:
        {
            return ___ice_ids(in, current);
        }
        case 3:
        {
            return ___ice_isA(in, current);
        }
        case 4:
        {
            return ___ice_ping(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
RobotPath::OptimalPath::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
RobotPath::OptimalPath::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
RobotPath::__patch(OptimalPathPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::RobotPath::OptimalPathPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::RobotPath::OptimalPath::ice_staticId(), v);
    }
}
